behaviors:
  StandingRagdoll:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1000
      buffer_size: 20000
      learning_rate: 0.0001
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 2
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 1024
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 200000
    max_steps: 50000000
    time_horizon: 150
    summary_freq: 25000
    threaded: false