default_settings: null
behaviors:
  StandingRagdoll:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1000
      buffer_size: 20000
      learning_rate: 0.0001
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 2
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 1024
      num_layers: 2
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 200000
    max_steps: 50000000
    time_horizon: 1250
    summary_freq: 25000
    threaded: false
    self_play: null
    behavioral_cloning: null
    framework: tensorflow
env_settings:
  env_path: env/PruebasTFG
  env_args: null
  base_port: 5005
  num_envs: 6
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
environment_parameters: null
checkpoint_settings:
  run_id: Test9
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
debug: false
